### ISSUE TITLE
Calls To Roninchain Being Rejected (403 Forbidden)

### ISSUE THREAD

**Issue by JonnyBoy333** [ZracheSs-xyZ/PayoutScript-xyZ#8]
It appears Sky Mavis has changed some requirements on calls made to the ronin chain rpc. Now whenever a request is made this error occurs:

```403 Client Error: Forbidden for url: https://proxy.roninchain.com/free-gas-rpc```

This is due to a new requirement to include a user-agent in the request headers. PR incoming...

**Comment by jf4nathan** [comment]
Any update on this?

**Comment by ZracheSs-xyZ** [comment]
Fix on last update
